# Generated by Django 2.2.1 on 2019-05-15 10:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190515_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignee',
            name='tasks',
            field=models.ManyToManyField(blank=True, to='api.Task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 15, 16, 11, 46, 529408)),
        ),
    ]
